# fly.toml file generated for animodibs on 2023-04-16T13:40:55+08:00

app = "animodibs"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 8080
  protocol = "tcp"